threads: 1
verbose: I
splits: [7, 2, 1]
names: [train, val, test]
delta: 0.1
epsilon: 0.1
runs: 1
solver: SCIP
techniques: [I1, S1]
output: results
max_sec: 100
data:
  - type: M
    data: tests/data/pipeline/drugs.tsv
    weights: tests/data/pipeline/drug_weights.tsv
    sim: ECFP
